# Generated by Django 3.1.7 on 2022-02-12 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220212_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='currentfund',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='targetfund',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.CreateModel(
            name='RecycleBin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('locationlat', models.CharField(blank=True, max_length=300, null=True)),
                ('locationlng', models.CharField(blank=True, max_length=300, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_activated', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reyclebins_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
